# To clean the volumes use:
#
# docker-compose down
# docker volume rm $(docker volume ls -q)

version: '3.7'

services:
  toro_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: toro_dev
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres

  toro_db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: toro_test
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgres

volumes:
  postgres:
    driver: local
