# To clean the volumes use:
#
# docker-compose down
# docker volume rm $(docker volume ls -q)

version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ilab_dev
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres

  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ilab_test
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgres

  redis:
    image: redis:5.0.9-buster
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
    driver: local
  redis:
    driver: local
